export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const TIMER_LOAD_SUCCESS = 'TIMER_LOAD_SUCCESS'
export const TIMER_SELECT = 'TIMER_SELECT'
export const TIMER_UNSELECT = 'TIMER_UNSELECT'
